name: PvPToggle
version: 1.0.0
main: com.adoray.pvptoggle.PvPToggle
description: PvP Toggle Plugin
author: AdoLife

commands:
  pvp:
    description: Toggle PvP on/off
    usage: /pvp
    aliases: [pvptoggle]

permissions:
  pvptoggle.use:
    description: Use /pvp command
    default: true