name: Build PvPToggle

on:
  push:
    branches: [ main, pvptoggle-plugin ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 21 Kur
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Maven ile Derle
        run: mvn clean package
        working-directory: ./PvPToggle

      - name: JAR Yükle
        uses: actions/upload-artifact@v4
        with:
          name: PvPToggle
          path: PvPToggle/target/PvPToggle.jar
